### ISSUE TITLE
packagist

### ISSUE THREAD

**Issue by TerraSkye** [tsingsun/yii2-graphql#1]
Your project isn't added to packagist.
also the "composer namespace" is wrong.

the namespace "yiisoft" is already in use.

therfore i advise to add it to packagist under : "tsingsun/yii2-graphql"

**Comment by tsingsun** [comment]
thank you,i have accepted the pull requests

**Comment by tsingsun** [comment]
the project is in developping,so don't  add to packagist

**Comment by TerraSkye** [comment]
Yes but now it cannot be invluded trough composer easely

**Comment by tsingsun** [comment]
OK,you can get it from composer use version "dev-master"
https://packagist.org/packages/tsingsun/yii2-graphql

**Comment by TerraSkye** [comment]
Thnx!
