### ISSUE TITLE
ActiveRecord to Type

### ISSUE THREAD

**Issue by miflinak** [tsingsun/yii2-graphql#4]
As ActiveRecordType was deleted, what is the prefered way to easily convert ActiveRecord to Type?

P.S. Your project looks promising and English documentation will be good addition.

**Comment by tsingsun** [comment]
i think ActiveRecordType is not a good way to implements like Yii RestfulController,in graphql query and mutation class separate, and if in ActiveRecord add too many code for grahpql need that will be little ugly. 
I consider providing a code tool later.
thanks for your advice,i am not good at English.but i will try my best.
