### ISSUE TITLE
Feature request: translate all docs/labels/strings to English

### ISSUE THREAD

**Issue by CedX** [tsingsun/yii2-graphql#5]
This library looks promising... but I'm French and the only languages I can read are French and English. So it would be a huge improvement in the adoption of this library if the documentation could be understood.
Thanks in advance.

**Comment by tsingsun** [comment]
Thank you for your advice. It will be in the plan

**Comment by CedX** [comment]
Very cool :) Thanks for the reply.

**Comment by tsingsun** [comment]
Readme has been translated

**Comment by CedX** [comment]
One more thanks :)

**Comment by CedX** [comment]
I close this issue as nearly every label were translated :+1:
