### ISSUE TITLE
Module Config

### ISSUE THREAD

**Issue by sganz** [tsingsun/yii2-graphql#6]
Trying to get a simple test working and using a Module to try it all out in an existing project. Ran into a simple typo on the Readme 

```       //graphql config
       'schemas' => [        
          'query' => [
              'user' => 'app\graphql\query\UsersQuery'
          ],
```
I think 'schemas' should be '**schema**' in the example code (may apply to the component example too).

Thanks, many more questions to ask :)  Thanks for all your work here as well.

Sandy

**Comment by sganz** [comment]
```
'components'=>[
...
          //if you use sample query except query contain interface,fragment,not need set
          //the key must same as your class definded
          'types'=>[          
              'Story'=>'yiiunit\extensions\graphql\objects\types\StoryType'
          ],
...
```

And I think here too for 'types' should be **'type'**

**Comment by tsingsun** [comment]
yes,my mistake. it should be schema in document and i will correct.
the types maybe keep to compatible the old version.

**Comment by sganz** [comment]
No worries! Been using the library for a few days, learning GQL at the same time. It's been a big help in integrating with my existing Yii2 app. 

Thanks again!
Sandy
